name: Deploy NestJS to GCP

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@029f5b4aeeeb58fdfe1410a5d17f967dacf36262 # v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          fingerprint: ${{ secrets.GCP_SSH_FINGERPRINT }}
          script: |
            cd ~/app

            # 최신 코드 가져오기
            git pull origin main

            # NestJS 컨테이너만 다시 빌드 후 실행
            docker compose up -d --build nest-api

            # 빌드 후 남은 안 쓰는 더미 이미지 정리
            docker image prune -f
